In [1]:
import numpy as np
import pandas as pd
import pickle   # сохранение модели
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import mean_squared_error as mse, r2_score as r2
from IPython.display import Image

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [3]:
df = pd.read_csv('test2.csv')
df.head()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2
0,4567,44,1.0,36.847630,19.094182,5.0,5,9.0,1970,0.036122,B,B,24,4378,0,1036.0,1,1,B
1,5925,62,1.0,42.493907,42.568133,10.0,7,17.0,2017,0.072158,B,B,2,629,1,NaN,0,0,A
2,960,27,2.0,59.463678,NaN,9.0,19,19.0,1977,0.211401,B,B,9,1892,0,NaN,0,1,B
3,3848,23,3.0,49.646030,33.893825,6.0,2,2.0,1965,0.014073,B,B,2,475,0,NaN,0,0,B
4,746,74,1.0,53.837056,NaN,1.0,8,17.0,1977,0.309479,B,B,35,7715,4,990.0,0,6,B

In [4]:
lr_model = pickle.load(open('lr_model.pkl', 'rb'))
dt_model = pickle.load(open('dt_model.pkl', 'rb'))
rf_model = pickle.load(open('rf_model.pkl', 'rb'))
gb_model = pickle.load(open('gb_model.pkl', 'rb'))

In [5]:
lifesquare_med = df['LifeSquare'].median()
df['LifeSquare'] = df['LifeSquare'].fillna(lifesquare_med)
Healthcare_1_med = df['Healthcare_1'].median()
df['Healthcare_1'] = df['Healthcare_1'].fillna(Healthcare_1_med)
missing_num = df.isnull().sum()
print(missing_num)

Id               0
DistrictId       0
Rooms            0
Square           0
LifeSquare       0
KitchenSquare    0
Floor            0
HouseFloor       0
HouseYear        0
Ecology_1        0
Ecology_2        0
Ecology_3        0
Social_1         0
Social_2         0
Social_3         0
Healthcare_1     0
Helthcare_2      0
Shops_1          0
Shops_2          0
dtype: int64

In [6]:
lr_pred = lr_model.predict(df.drop(columns=['DistrictId', 'Ecology_2', 'Ecology_3', 'Id', 'Shops_2', 'Social_2'], axis=1))
lr = pd.DataFrame(lr_pred, columns=['predictions'])
lr.insert(0, 'Id', df['Id'])
lr.to_csv('lr_pred2.csv', index=False)

In [7]:
dt_pred = dt_model.predict(df.drop(columns=['DistrictId', 'Ecology_2', 'Ecology_3', 'Id', 'Shops_2', 'Social_2'], axis=1))
dt = pd.DataFrame(dt_pred, columns=['predictions'])
dt.insert(0, 'Id', df['Id'])
dt.to_csv('dt_pred2.csv', index=False)

In [8]:
rf_pred = rf_model.predict(df.drop(columns=['DistrictId', 'Ecology_2', 'Ecology_3', 'Id', 'Shops_2', 'Social_2'], axis=1))
rf = pd.DataFrame(rf_pred, columns=['predictions'])
rf.insert(0, 'Id', df['Id'])
rf.to_csv('rf_pred2.csv', index=False)

In [9]:
# gb_pred = gb_model.predict(df.drop(columns=['DistrictId', 'Ecology_2', 'Ecology_3', 'Id', 'Shops_2', 'Social_2'], axis=1))
# pd.DataFrame(gb_pred, columns=['predictions']).to_csv('gb_pred2.csv', index=True)